server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
#    url: jdbc:mysql://localhost:3306/jntt
    url: jdbc:mysql://39.107.56.242:3306/jntt
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.jntt.user.pojo